# Disable the "core" dotnet plugins
disablePlugins:
  - lando-dotnet

# Make sure we are dogfooding this plugin for testing purposes
plugins:
  "@lando/dotnet": /home/runner/work/dotnet/dotnet

# Disable metrics reporting
stats:
  - report: false
    url: https://metrics.lando.dev
